name: 00 - Main CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

  jobs:
  build:
    name: build
    uses: ./.github/workflows/build.yml
    secrets: inherit